[package]
name = "fast_struct"
version = "1.3.0"
edition = "2024"

[workspace]
members = [
    "./tests"
]

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }
